# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  fs_permissions = [{ access = "read-write", path = "./scripts" }]
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  test = "test"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${ALCHEMY_API_KEY}" }
  sepolia = { key = "${ALCHEMY_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 200
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  mainnet = "https://settlus-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  sepolia = "https://settlus-septestnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
